import type { ServiceProvider } from "./service-providers";

const cloudflareSource =
  "https://developers.cloudflare.com/agents/model-context-protocol/cloudflare/servers-for-cloudflare/";

// Official provider documentation and public OAuth metadata checked 2026-09-12.
// Metadata compatibility does not imply an authenticated account or tool test.
export const INFRA_SERVICE_PROVIDERS: ServiceProvider[] = [
  {
    id: "github",
    name: "GitHub",
    url: "https://api.githubcopilot.com/mcp/",
    category: "Code & Qualität",
    description: "Repositories, Issues, Pull Requests und CI-Läufe bearbeiten.",
    source: "https://github.com/github/github-mcp-server/blob/main/docs/host-integration.md",
    setupRequired:
      "GitHub verlangt eine eigene registrierte Anvil-App mit zusätzlicher Anmeldelogik oder einen persönlichen Zugriffstoken. Die automatische Client-Registrierung wird nicht unterstützt.",
  },
  {
    id: "gitlab",
    name: "GitLab",
    url: "https://gitlab.com/api/v4/mcp",
    category: "Code & Qualität",
    description: "Projekte, Issues und Merge Requests mit GitLab verbinden.",
    source: "https://docs.gitlab.com/user/model_context_protocol/mcp_server/",
    note: "Beta. Der MCP-Zugriff muss in der obersten GitLab-Gruppe freigegeben sein. Eigene GitLab-Instanzen lassen sich über ihre Dienstadresse ergänzen.",
  },
  {
    id: "sentry",
    name: "Sentry",
    url: "https://mcp.sentry.dev/mcp",
    category: "Code & Qualität",
    description: "Fehler, Stacktraces, Releases und Leistungsprobleme untersuchen.",
    source: "https://github.com/getsentry/sentry-mcp",
    note: "Organisation, Projekte und verfügbare Fähigkeiten werden bei Sentry freigegeben.",
  },
  {
    id: "posthog",
    name: "PostHog",
    url: "https://mcp.posthog.com/mcp",
    category: "Code & Qualität",
    description: "Produktanalysen, Fehler, Feature Flags und Experimente auswerten.",
    source: "https://posthog.com/docs/model-context-protocol",
    note: "Die Anmeldung wählt die passende Datenregion. KI-Funktionen können eine Freigabe für KI-Datenverarbeitung erfordern und Kosten verursachen.",
  },
  {
    id: "supabase",
    name: "Supabase",
    url: "https://mcp.supabase.com/mcp",
    category: "Datenbanken",
    description: "Datenbanken, Tabellen, Abfragen und Entwicklungsprojekte verwalten.",
    source: "https://supabase.com/docs/guides/ai-tools/mcp",
    note: "Für einzelne Projekte oder reinen Lesezugriff kann eine entsprechend eingeschränkte Dienstadresse verwendet werden.",
  },
  {
    id: "neon",
    name: "Neon",
    url: "https://mcp.neon.tech/mcp",
    category: "Datenbanken",
    description: "Postgres-Projekte, Datenbankzweige und SQL-Abfragen nutzen.",
    source: "https://neon.com/docs/ai/neon-mcp-server",
    note: "Mit dem Neon-Konto anmelden und die benötigten Berechtigungen freigeben.",
  },
  {
    id: "vercel",
    name: "Vercel",
    url: "https://mcp.vercel.com/",
    category: "Hosting & Cloud",
    description: "Projekte, Deployments, Build-Protokolle und Webanalysen bearbeiten.",
    source: "https://vercel.com/docs/agent-resources/vercel-mcp",
    note: "Zugriff auf die gewünschten Vercel-Projekte im Browser freigeben.",
  },
  {
    id: "netlify",
    name: "Netlify",
    url: "https://netlify-mcp.netlify.app/mcp",
    category: "Hosting & Cloud",
    description: "Webprojekte, Veröffentlichungen und Netlify-Ressourcen verwalten.",
    source: "https://docs.netlify.com/build/build-with-ai/agent-setup-guides/agent-setup-overview/",
  },
  {
    id: "render",
    name: "Render",
    url: "https://mcp.render.com/mcp",
    category: "Hosting & Cloud",
    description: "Dienste, Deployments, Datenbanken, Protokolle und Metriken verwalten.",
    source: "https://render.com/docs/mcp-server",
    setupRequired:
      "Render bietet Browser-Anmeldung für registrierte Clients, aber keine automatische Client-Registrierung. Für Anvil wird eine eigene freigegebene Client-ID oder eine Verbindung mit API-Schlüssel benötigt.",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    url: "https://mcp.cloudflare.com/mcp",
    category: "Hosting & Cloud",
    description: "Cloudflare-Dienste wie DNS, Workers, R2 und Zero Trust verwalten.",
    source: cloudflareSource,
    note: "Die Werkzeuge search und execute bündeln viele Funktionen. Den Zugriff deshalb auch bei Cloudflare auf die benötigten Rechte beschränken.",
  },
  {
    id: "cloudflare-bindings",
    name: "Cloudflare Workers Bindings",
    url: "https://bindings.mcp.cloudflare.com/mcp",
    category: "Hosting & Cloud",
    description: "Workers mit Speicher, KI und Rechendiensten verbinden.",
    source: cloudflareSource,
  },
  {
    id: "cloudflare-builds",
    name: "Cloudflare Workers Builds",
    url: "https://builds.mcp.cloudflare.com/mcp",
    category: "Hosting & Cloud",
    description: "Builds von Workers prüfen und verwalten.",
    source: cloudflareSource,
  },
  {
    id: "cloudflare-observability",
    name: "Cloudflare Observability",
    url: "https://observability.mcp.cloudflare.com/mcp",
    category: "Code & Qualität",
    description: "Anwendungsprotokolle und Analysen zur Fehlersuche nutzen.",
    source: cloudflareSource,
  },
  {
    id: "cloudflare-radar",
    name: "Cloudflare Radar",
    url: "https://radar.mcp.cloudflare.com/mcp",
    category: "Hosting & Cloud",
    description: "Internettrends, Netzwerkverkehr und URL-Scans untersuchen.",
    source: cloudflareSource,
  },
  {
    id: "cloudflare-containers",
    name: "Cloudflare Containers",
    url: "https://containers.mcp.cloudflare.com/mcp",
    category: "Hosting & Cloud",
    description: "Abgeschirmte Entwicklungsumgebungen in der Cloud starten.",
    source: cloudflareSource,
  },
  {
    id: "cloudflare-browser",
    name: "Cloudflare Browser Run",
    url: "https://browser.mcp.cloudflare.com/mcp",
    category: "Hosting & Cloud",
    description: "Webseiten abrufen, in Markdown umwandeln und Bildschirmfotos erstellen.",
    source: cloudflareSource,
  },
  {
    id: "cloudflare-logpush",
    name: "Cloudflare Logpush",
    url: "https://logs.mcp.cloudflare.com/mcp",
    category: "Code & Qualität",
    description: "Den Zustand von Logpush-Aufträgen überprüfen.",
    source: cloudflareSource,
  },
  {
    id: "cloudflare-ai-gateway",
    name: "Cloudflare AI Gateway",
    url: "https://ai-gateway.mcp.cloudflare.com/mcp",
    category: "Code & Qualität",
    description: "KI-Anfragen und Antworten in Gateway-Protokollen untersuchen.",
    source: cloudflareSource,
  },
  {
    id: "cloudflare-ai-search",
    name: "Cloudflare AI Search",
    url: "https://autorag.mcp.cloudflare.com/mcp",
    category: "Datenbanken",
    description: "Dokumente aus vorhandenen AI-Search-Sammlungen durchsuchen.",
    source: cloudflareSource,
  },
  {
    id: "cloudflare-auditlogs",
    name: "Cloudflare Audit Logs",
    url: "https://auditlogs.mcp.cloudflare.com/mcp",
    category: "Code & Qualität",
    description: "Änderungsprotokolle abfragen und Prüfberichte erstellen.",
    source: cloudflareSource,
  },
  {
    id: "cloudflare-dns-analytics",
    name: "Cloudflare DNS Analytics",
    url: "https://dns-analytics.mcp.cloudflare.com/mcp",
    category: "Hosting & Cloud",
    description: "DNS-Leistung und Konfigurationsprobleme untersuchen.",
    source: cloudflareSource,
  },
  {
    id: "cloudflare-dex",
    name: "Cloudflare Digital Experience",
    url: "https://dex.mcp.cloudflare.com/mcp",
    category: "Hosting & Cloud",
    description: "Erreichbarkeit und Nutzung wichtiger Anwendungen überwachen.",
    source: cloudflareSource,
  },
  {
    id: "cloudflare-casb",
    name: "Cloudflare One CASB",
    url: "https://casb.mcp.cloudflare.com/mcp",
    category: "Code & Qualität",
    description: "Sicherheitsprobleme in angebundenen Cloud-Anwendungen erkennen.",
    source: cloudflareSource,
  },
  {
    id: "cloudflare-graphql",
    name: "Cloudflare GraphQL Analytics",
    url: "https://graphql.mcp.cloudflare.com/mcp",
    category: "Hosting & Cloud",
    description: "Cloudflare-Analysedaten gezielt abfragen.",
    source: cloudflareSource,
  },
];
