import assert from "node:assert/strict";
import { test } from "node:test";
import path from "node:path";
import { createServer } from "vite";

test("imported folder skills retain resources, identity, edits and explicit removal across hydration", async t => {
  const server = await createServer({ configFile: false, root: process.cwd(), resolve: { alias: { "@": path.resolve("src") } }, ssr: { external: ["react", "react-dom", "zustand", "js-yaml"] }, optimizeDeps: { noDiscovery: true, include: [] }, server: { middlewareMode: true, hmr: false, watch: null }, appType: "custom" });
  t.after(() => server.close());
  const { useIde } = await server.ssrLoadModule("/src/store/ide.ts");
  const { useLearn, hydrateLearnFromFiles, agentLearn, LEARN_DEFAULTS } = await server.ssrLoadModule("/src/lib/learn.ts");
  const warnings = console.warn;
  console.warn = (...args: unknown[]) => { if (!String(args[0]).startsWith("[zustand persist middleware]")) warnings(...args); };
  t.after(() => { console.warn = warnings; });
  const manifest = ".anvil/skills/long-standard-guide/SKILL.md";
  const source = `---\nname: long-standard-guide\ndescription: Read the complete guide and supporting reference.\nlicense: MIT\n---\n${"Preserve every instruction. ".repeat(600)}`;
  const files = { [manifest]: source, ".anvil/skills/long-standard-guide/references/check.md": "Reference expected to survive.", ".anvil/skills/long-standard-guide/scripts/check.js": "throw new Error('must not execute')" };
  useIde.setState({ workspaceCwd: "I:/SkillPackageTestA", workspaceEpoch: 1, files, dirty: {}, pendingDiffs: [], writeFile: (file: string, body: string) => useIde.setState({ files: { ...useIde.getState().files, [file]: body } }), deleteFile: (file: string) => { const next = { ...useIde.getState().files }; delete next[file]; useIde.setState({ files: next }); } });
  useLearn.setState({ on: true, prefs: { ...LEARN_DEFAULTS }, skills: [], forgotten: [], activeSkills: [] });
  hydrateLearnFromFiles(files);
  const first = useLearn.getState().skills[0];
  assert.ok(first.body.length > 8000);
  hydrateLearnFromFiles(files);
  assert.equal(useLearn.getState().skills.length, 1);
  assert.equal(useLearn.getState().skills[0].id, first.id);
  const run = await agentLearn("run", { name: first.id });
  assert.equal(run.baseDirectory, ".anvil/skills/long-standard-guide");
  assert.ok(run.resources.includes(".anvil/skills/long-standard-guide/references/check.md"));
  assert.equal(run.body, first.body);
  useLearn.getState().writeSkill({ name: first.name, when: first.when, body: first.body + "\nUpdated instruction.", scope: "project" });
  assert.match(useIde.getState().files[manifest], /license: MIT/);
  assert.match(useIde.getState().files[manifest], /Updated instruction/);
  assert.equal(useIde.getState().files[".anvil/skills/long-standard-guide/references/check.md"], files[".anvil/skills/long-standard-guide/references/check.md"]);
  useLearn.getState().forgetSkill(first.id);
  hydrateLearnFromFiles(files);
  assert.equal(useLearn.getState().skills.length, 0, "regular reload must not undo removal");
  hydrateLearnFromFiles(files, [manifest]);
  assert.equal(useLearn.getState().skills.length, 1, "explicit reimport permits reinstall");
  useIde.setState({ workspaceCwd: "I:/SkillPackageTestB" });
  hydrateLearnFromFiles(files);
  const second = useLearn.getState().skills.find((skill: { ws?: string }) => skill.ws?.endsWith("skillpackagetestb"));
  assert.notEqual(second.id, first.id);
  hydrateLearnFromFiles(files);
  assert.equal(useLearn.getState().skills.length, 2);
  assert.equal(useLearn.getState().skills.find((skill: { ws?: string }) => skill.ws?.endsWith("skillpackagetestb")).id, second.id);
});
