import type { ToolCompatibility } from "@/lib/tool-compat";
import type { ToolLearning, ToolLearningState } from "@/lib/tool-learning";
import { type LlmProvider } from "@/lib/providers";

import { type InputMap } from "@/lib/input-map";
import { type Chord, type KeyId } from "@/lib/keymap";
import type { CompactMode } from "@/lib/compact";
import type { ThinkingMode } from "@/lib/llm-options";
import type { McpServer } from "@/lib/mcp";
import { type SurfaceMode } from "@/lib/surface";
import type { LspHit } from "@/lib/lsp";
import type { TestHit } from "@/lib/test-parse";

import type { AfterWrite } from "@/lib/harness";
import { type PlanWho } from "@/lib/plan";

import { type SessionJournal } from "@/lib/session";
import { type AgentJob } from "@/lib/agent-ask";

import type { FileChange } from "@/lib/diff";

export type LlmSlot = {
  authMode?: "abo" | "key";
  contextAuto?: boolean;
  baseUrl: string;
  model: string;
  context: number;
  thinking: ThinkingMode;
  compact: CompactMode;
  temperature: number;
  maxOut: number;
};

export type LlmProfile = LlmSlot & {
  toolMode?: ToolCompatibility;
  id: string;
  name: string;
  provider: LlmProvider;
};

export type ChatRole = "user" | "assistant";

export type PanelId = "files" | "code" | "agent" | "output" | "trail";

export type ThemeName = "dark" | "light";

export type MotionLevel = "off" | "reduced" | "full";

export type SplitMode = "auto" | "side" | "stack";

export type SidebarId = "files" | "search" | "git" | "ext" | "learn" | "tests" | "ref" | "mcp" | null;

export type PaletteMode = "files" | "commands" | "symbols" | null;

export type AgentMode = "ask" | "agent";

export type OutputDock = "bottom" | "side";

export type StorageMode = "browser" | "disk";

export type DebugFrame = { path: string; line: number; fn: string };

export type McpCallLog = {
  at: number;
  server: string;
  name: string;
  ok: boolean;
  detail: string;
  image?: string;
};

export type McpView = { text: string; image?: string; at: number };

export type DebugState = {
  active: boolean;
  paused: boolean;
  path: string | null;
  line: number;
  reason: string;
  stack: DebugFrame[];
  locals: Record<string, string>;
  watches: string[];
  watchValues: Record<string, string>;
  lastEval: string;
};

export type FileDiff = {
  path: string;
  before: string;
  after: string;
  source?: "round" | "propose";
};

export type PlanStep = { text: string; status: "todo" | "run" | "ok" | "err" };

export type Checkpoint = {
  id: string;
  at: number;
  label: string;
  files: Record<string, string>;
  dirs: string[];
};

export type ChatVoice = "agent" | "helper";

export type ChatMsg = {
  id: string;
  role: ChatRole;
  voice?: ChatVoice;
  content: string;
  tools?: string[];
  steps?: AgentStep[];
  thinking?: string;
  images?: string[];
  plan?: PlanStep[];
  planLocked?: boolean;
  checkpointId?: string;
  at?: number;
  ms?: number;
  changes?: FileChange[];
  lastRun?: {
    id?: string;
    ok: boolean;
    path: string;
    stdout: string;
    stderr: string;
    attempt: number;
    max: number;
    graphical?: boolean;
    running?: boolean;
  };
  lastTests?: { ok: boolean; pass: number; fail: number; running?: boolean };
  harness?: string;
};

export type AgentStep = {
  id: string;
  name: string;
  detail: string;
  status: "run" | "ok" | "err";
  image?: string;
  path?: string;
  code?: string;
  before?: string;
  at?: number;
  ms?: number;
};

export type GitCommit = {
  id: string;
  message: string;
  at: number;
  paths: string[];
  snap?: Record<string, string>;
};

export type RunResult = {
  ok: boolean;
  stdout: string;
  stderr: string;
  duration: number;
  label: string;
  html?: string;
  stage?: { kind: "html" | "window" | "log"; out?: string; id?: string; state?: import("@/lib/canvas/protocol").CanvasState };
};

export type Panels = Record<PanelId, boolean>;

export type IdeState = {
  files: Record<string, string>;
  openPaths: string[];
  activePath: string | null;
  dirty: Record<string, boolean>;
  chat: ChatMsg[];
  commits: GitCommit[];
  output: RunResult[];
  running: boolean;
  testsRunning: boolean;
  testResults: Record<string, TestHit>;
  agentBusy: boolean;
  agentStartedAt: number;
  agentJob: AgentJob | null;
  panels: Panels;
  settingsOpen: boolean;
  harnessBoardOpen: boolean;
  harnessBoardGrid: boolean;
  harnessBoardSnap: boolean;
  theme: ThemeName;
  locale: "de" | "en";
  motion: MotionLevel;
  fontSize: number;
  tabSize: 2 | 4 | 8;
  lineNumbers: boolean;
  wordWrap: boolean;
  editorMinimap: boolean;
  editorSticky: boolean;
  editorGuides: boolean;
  editorWheelZoom: boolean;
  suggestOn: boolean;
  insertSpaces: boolean;
  formatOnSave: boolean;
  autoPreview: boolean;
  autoAcceptDiffs: boolean;
  autoRunAgent: boolean;
  planWho: PlanWho;
  runLoop: boolean;
  testLoop: boolean;
  graphLoop: boolean;
  engineLoop: boolean;
  loopTries: number;
  harnessAfterWrite: AfterWrite;
  harnessMaxRounds: number;
  graphSees: number;
  liveRun: boolean;
  liveEditor: boolean;
  mcpStream: boolean;
  showStatusBar: boolean;
  openOutputOnRun: boolean;
  runInWindow: boolean;
  runHtml: boolean;
  autoUpdate: boolean;
  splitMode: SplitMode;
  llmProvider: LlmProvider;
  llmAuthMode: "abo" | "key";
  llmBaseUrl: string;
  llmModel: string;
  llmApiKey: string;
  llmContext: number;
  llmContextAuto: boolean;
  llmThinking: ThinkingMode;
  llmCompact: CompactMode;
  llmTemperature: number;
  llmMaxOut: number;
  llmRetries: number;
  llmHardStopMin: number;
  llmSlots: Record<string, LlmSlot>;
  llmProfiles: LlmProfile[];
  llmToolModes: Record<string, ToolCompatibility>;
  llmToolLearning: ToolLearningState;
  sessionTokens: { prompt: number; completion: number };
  sessionJournal: SessionJournal;
  sidebar: SidebarId;
  palette: PaletteMode;
  pendingDiffs: FileDiff[];
  cursor: { line: number; col: number };
  selection: { startLine: number; startCol: number; endLine: number; endCol: number };
  searchQuery: string;
  agentMode: AgentMode;
  agentRules: string;
  attached: string[];
  agentDraft: string;
  sidebarWidth: number;
  agentWidth: number;
  outputHeight: number;
  outputWidth: number;
  outputDock: OutputDock;
  outputPopout: boolean;
  trailWidth: number;
  trailThinkH: number;
  trailInChat: boolean;
  autoHw: boolean;
  hwNote: string;
  runPopout: boolean;
  previewOpen: boolean;
  runPath: string | null;
  pluginDisabled: string[];
  pluginKnown: string[];
  pluginStatus: string;
  pluginConfig: Record<string, unknown>;
  pluginProblems: { path: string; line: number; text: string; source: string }[];
  lspProblems: LspHit[];
  runProblems: LspHit[];
  companionProblems: LspHit[];
  compileProblems: LspHit[];
  mcpServers: McpServer[];
  activeSurfaceId: string;
  surfaceMode: SurfaceMode;
  mcpLog: McpCallLog[];
  mcpView: Record<string, McpView>;
  companionUrl: string;
  companionKeep: boolean;
  netCompiler: boolean;
  lspEnabled: Record<string, boolean>;
  lspTimeout: number;
  lspMaxFiles: number;
  lspLog: { at: number; ok: boolean; text: string }[];
  engineLink: { label: string; ok: boolean } | null;
  checkpoints: Checkpoint[];
  agentInbox: string | null;
  agentQueue: string[];
  pendingAsk: { path: string; text: string } | null;
  recentPaths: string[];
  flashPath: string | null;
  peek: { word: string; defs: { path: string; line: number; text: string }[] } | null;
  jumpStack: { path: string; line: number }[];
  jumpIndex: number;
  closedTabs: string[];
  breakpoints: Record<string, number[]>;
  debug: DebugState;
  notice: string;
  undo: Record<string, string[]>;
  dirs: string[];
  collapsed: string[];
  diskName: string;
  workspaceCwd: string;
  setupDone: boolean;
  backupName: string;
  storageMode: StorageMode;
  autoSaveDisk: boolean;
  loadOnStart: boolean;
  githubRepo: string;
  githubToken: string;
  inputMap: InputMap;
  keyMap: Record<KeyId, Chord>;
  togglePanel: (id: PanelId) => void;
  setPanels: (panels: Panels) => void;
  setSettingsOpen: (v: boolean) => void;
  setHarnessBoardOpen: (v: boolean) => void;
  setHarnessBoardGrid: (v: boolean) => void;
  setHarnessBoardSnap: (v: boolean) => void;
  setTheme: (theme: ThemeName) => void;
  setLocale: (locale: "de" | "en") => void;
  setMotion: (v: MotionLevel) => void;
  setFontSize: (n: number) => void;
  setTabSize: (n: 2 | 4 | 8) => void;
  setLineNumbers: (v: boolean) => void;
  setWordWrap: (v: boolean) => void;
  setEditorMinimap: (v: boolean) => void;
  setEditorSticky: (v: boolean) => void;
  setEditorGuides: (v: boolean) => void;
  setEditorWheelZoom: (v: boolean) => void;
  setSuggestOn: (v: boolean) => void;
  setInsertSpaces: (v: boolean) => void;
  setFormatOnSave: (v: boolean) => void;
  setAutoPreview: (v: boolean) => void;
  setAutoAcceptDiffs: (v: boolean) => void;
  setAutoRunAgent: (v: boolean) => void;
  setPlanWho: (v: PlanWho) => void;
  setRunLoop: (v: boolean) => void;
  setTestLoop: (v: boolean) => void;
  setGraphLoop: (v: boolean) => void;
  setEngineLoop: (v: boolean) => void;
  setLoopTries: (n: number) => void;
  setHarnessAfterWrite: (v: AfterWrite) => void;
  setHarnessMaxRounds: (n: number) => void;
  setGraphSees: (n: number) => void;
  setLiveRun: (v: boolean) => void;
  setLiveEditor: (v: boolean) => void;
  setMcpStream: (v: boolean) => void;
  setShowStatusBar: (v: boolean) => void;
  setOpenOutputOnRun: (v: boolean) => void;
  setRunInWindow: (v: boolean) => void;
  setRunHtml: (v: boolean) => void;
  setAutoUpdate: (v: boolean) => void;
  setRunPopout: (v: boolean) => void;
  setRunPath: (path: string | null) => void;
  setSplitMode: (v: SplitMode) => void;
  setLlmProvider: (v: LlmProvider, mode?: "abo" | "key") => void;
  setLlmAuthMode: (v: "abo" | "key") => void;
  setLlmBaseUrl: (v: string) => void;
  setLlmModel: (v: string) => void;
  setLlmToolMode: (mode: ToolCompatibility) => void;
  updateToolLearning: (key: string, update: (state: ToolLearning) => ToolLearning) => void;
  setLlmApiKey: (v: string) => void;
  setLlmContext: (n: number) => void;
  setLlmContextAuto: (v: boolean) => void;
  setLlmThinking: (v: ThinkingMode) => void;
  setLlmCompact: (v: CompactMode) => void;
  setLlmTemperature: (n: number) => void;
  setLlmMaxOut: (n: number) => void;
  setLlmRetries: (n: number) => void;
  setLlmHardStopMin: (n: number) => void;
  saveLlmProfile: (name: string) => void;
  applyLlmProfile: (id: string) => void;
  deleteLlmProfile: (id: string) => void;
  addAgentStep: (step: Omit<AgentStep, "id">) => void;
  appendThinking: (s: string) => void;
  addSessionTokens: (prompt: number, completion: number) => void;
  setSessionJournal: (j: SessionJournal) => void;
  setSidebar: (v: SidebarId) => void;
  setPalette: (v: PaletteMode) => void;
  setCursor: (line: number, col: number) => void;
  setSelection: (startLine: number, startCol: number, endLine: number, endCol: number) => void;
  setSearchQuery: (v: string) => void;
  setAgentMode: (v: AgentMode) => void;
  setAgentRules: (v: string) => void;
  setAttached: (v: string[]) => void;
  setAgentDraft: (v: string) => void;
  setSidebarWidth: (n: number) => void;
  setAgentWidth: (n: number) => void;
  setOutputHeight: (n: number) => void;
  setOutputWidth: (n: number) => void;
  setOutputDock: (v: OutputDock) => void;
  setOutputPopout: (v: boolean) => void;
  setTrailWidth: (n: number) => void;
  setTrailThinkH: (n: number) => void;
  setTrailInChat: (v: boolean) => void;
  setAutoHw: (v: boolean) => void;
  setHwNote: (v: string) => void;
  revealOutput: () => void;
  setPreviewOpen: (v: boolean) => void;
  togglePlugin: (id: string) => void;
  setPluginKnown: (ids: string[]) => void;
  setPluginDisabled: (ids: string[]) => void;
  setPluginStatus: (v: string) => void;
  setPluginConfig: (v: Record<string, unknown>) => void;
  setPluginProblems: (v: { path: string; line: number; text: string; source: string }[]) => void;
  setLspProblems: (v: LspHit[]) => void;
  setCompanionProblems: (v: LspHit[]) => void;
  setCompileProblems: (v: LspHit[]) => void;
  setMcpServers: (v: McpServer[]) => void;
  setActiveSurface: (id: string) => void;
  setSurfaceMode: (v: SurfaceMode) => void;
  setMcpContext: (id: string, context: Record<string, string>) => void;
  pushMcpLog: (e: McpCallLog) => void;
  setMcpView: (id: string, v: McpView) => void;
  clearMcpLog: () => void;
  setCompanionUrl: (v: string) => void;
  setCompanionKeep: (v: boolean) => void;
  setNetCompiler: (v: boolean) => void;
  setLspEnabled: (id: string, on: boolean) => void;
  setLspTimeout: (n: number) => void;
  setLspMaxFiles: (n: number) => void;
  pushLspLog: (ok: boolean, text: string) => void;
  clearLspLog: () => void;
  setEngineLink: (v: { label: string; ok: boolean } | null) => void;
  setChatLastRun: (v: ChatMsg["lastRun"]) => void;
  setChatLastTests: (v: ChatMsg["lastTests"]) => void;
  setChatHarness: (v: string) => void;
  failRunningSteps: () => void;
  openRoundDiff: (path: string, checkpointId?: string) => void;
  pushCheckpoint: (label: string) => string;
  patchFiles: (next: Record<string, string>, opts?: { quiet?: boolean }) => number;
  restoreCheckpoint: (id: string) => boolean;
  setChatChanges: (changes: FileChange[]) => void;
  setPendingAsk: (v: { path: string; text: string } | null) => void;
  revealPath: (path: string) => void;
  cycleTab: (dir: 1 | -1) => void;
  reorderTabs: (from: string, to: string) => void;
  setPeek: (v: { word: string; defs: { path: string; line: number; text: string }[] } | null) => void;
  pushJump: () => void;
  goJump: (dir: -1 | 1) => void;
  reopenTab: () => void;
  setChatPlan: (steps: PlanStep[], id?: string) => void;
  updatePlanStep: (i: number, status: PlanStep["status"], id?: string) => void;
  pushAgent: (text: string, steal?: boolean) => void;
  clearAgentInbox: () => void;
  toggleBreakpoint: (path: string, line: number, on?: boolean) => void;
  setDebug: (p: Partial<DebugState>) => void;
  addWatch: (expr: string) => void;
  removeWatch: (expr: string) => void;
  setDebugWatches: (v: Record<string, string>) => void;
  setDebugEval: (v: string) => void;
  setNotice: (msg: string) => void;
  undoFile: (path: string) => void;
  renameFile: (from: string, to: string) => void;
  clearChat: (keep?: boolean) => void;
  removeChat: (id: string) => void;
  proposeFiles: (next: Record<string, string>) => void;
  acceptDiff: (path: string) => void;
  rejectDiff: (path: string) => void;
  rejectHunk: (path: string, hunk: number) => void;
  acceptAllDiffs: () => void;
  rejectAllDiffs: () => void;
  openFile: (path: string) => void;
  closeFile: (path: string, opts?: { force?: boolean }) => void;
  setContent: (path: string, content: string) => void;
  writeFile: (path: string, content: string, opts?: { quiet?: boolean }) => void;
  deleteFile: (path: string) => void;
  createFolder: (path: string) => void;
  deleteDir: (path: string) => void;
  movePath: (from: string, dest: string) => void;
  duplicateFile: (path: string) => void;
  toggleCollapsed: (path: string) => void;
  applyFiles: (next: Record<string, string>, dirs?: string[], opts?: { keepDirty?: boolean }) => void;
  addChat: (msg: Omit<ChatMsg, "id">) => void;
  startAssistant: (opts?: { voice?: ChatVoice }) => void;
  appendAssistant: (s: string) => void;
  finalizeAssistant: (reply: string, tools?: string[], options?: { replace?: boolean }) => void;
  setDiskName: (v: string) => void;
  setWorkspaceCwd: (v: string) => void;
  setSetupDone: (v: boolean) => void;
  setBackupName: (v: string) => void;
  setStorageMode: (v: StorageMode) => void;
  setAutoSaveDisk: (v: boolean) => void;
  setLoadOnStart: (v: boolean) => void;
  setGithubRepo: (v: string) => void;
  setGithubToken: (v: string) => void;
  setInputMap: (v: InputMap) => void;
  resetInputMap: () => void;
  setKeyBind: (id: KeyId, chord: Chord) => void;
  resetKeyMap: () => void;
  setAgentBusy: (v: boolean) => void;
  setAgentJob: (v: AgentJob | null) => void;
  setTestsRunning: (v: boolean) => void;
  mergeTestResults: (hits: TestHit[]) => void;
  pushOutput: (r: RunResult) => void;
  clearOutput: () => void;
  setRunning: (v: boolean) => void;
  commit: (message: string) => void;
  checkout: (id: string) => void;
  revertFile: (path: string) => void;
  resetWorkspace: () => void;
  resetSettings: () => void;
};
