import assert from "node:assert/strict";
import { test } from "node:test";
import { createServer } from "vite";
import path from "node:path";

test("editor follows agent writes without persisting streaming drafts or following reads", async (t) => {
  const values = new Map();
  globalThis.localStorage = { getItem: (k) => values.get(k) ?? null, setItem: (k, v) => values.set(k, v), removeItem: (k) => values.delete(k) };
  globalThis.window = Object.assign(new EventTarget(), { localStorage, setTimeout, clearTimeout });
  globalThis.document = Object.assign(new EventTarget(), { documentElement: { lang: "de" } });
  const server = await createServer({ configFile: false, root: process.cwd(), resolve: { alias: { "@": path.resolve("src") } }, server: { middlewareMode: true, hmr: false }, appType: "custom" });
  const { useIde } = await server.ssrLoadModule("/src/store/ide.ts");
  const { useIntern } = await server.ssrLoadModule("/src/lib/intern.ts");
  useIntern.getState().setPrefs({ on: false, autoHeal: false });
  const { beginAgent, abortAgent } = await server.ssrLoadModule("/src/lib/abort.ts");
  const live = await server.ssrLoadModule("/src/lib/live-write.ts");
  const { applyWorkspace } = await server.ssrLoadModule("/src/lib/chat-session.ts");
  t.after(async () => {
    live.resetLiveWrite();
    t.mock.timers.reset();
    const { flushPersistence } = await server.ssrLoadModule("/src/lib/persist-storage.ts");
    await flushPersistence().catch(() => {});
    await server.close();
    delete globalThis.window; delete globalThis.document; delete globalThis.localStorage;
  });
  useIde.setState({ files: { "a.ts": "old a", "b.ts": "old b" }, activePath: "a.ts", openPaths: ["a.ts"], liveEditor: true, agentBusy: true, autoSaveDisk: false, autoPreview: false, workspaceCwd: "", pendingDiffs: [] });
  beginAgent(); live.resetLiveWrite();
  t.mock.timers.enable({ apis: ["setTimeout"] });
  live.applyLiveDraft("read_file", '{"path":"b.ts"}');
  t.mock.timers.tick(50);
  assert.equal(useIde.getState().activePath, "a.ts");
  live.applyLiveDraft("write_file", '{"path":"b.ts","content":"new');
  t.mock.timers.tick(50);
  assert.equal(useIde.getState().activePath, "b.ts");
  assert.equal(useIde.getState().files["b.ts"], "old b");
  assert.equal(live.useLivePreview.getState().streaming, true);
  const { agentGen } = await server.ssrLoadModule("/src/lib/abort.ts");
  live.finishLiveWrite(agentGen());
  assert.equal(live.useLivePreview.getState().streaming, false);
  assert.equal(live.useLivePreview.getState().draft.path, "b.ts", "finished draft remains available to expand manually");
  live.applyLiveDraft("write_file", '{"path":"new.ts","content":"partial');
  t.mock.timers.tick(50);
  assert.equal(live.useLivePreview.getState().streaming, true, "next write reopens the preview");
  assert.equal(live.useLivePreview.getState().draft.path, "new.ts");
  assert.equal("new.ts" in useIde.getState().files, false);
  for (const autoAcceptDiffs of [false, true]) {
    useIde.setState({ autoAcceptDiffs });
    await applyWorkspace({ op: "write", path: "a.ts", content: `updated ${autoAcceptDiffs}` });
    assert.equal(useIde.getState().activePath, "a.ts");
    await applyWorkspace({ op: "write", path: "new.ts", content: `complete ${autoAcceptDiffs}` });
    assert.equal(useIde.getState().activePath, "new.ts");
    assert.equal(useIde.getState().files["new.ts"], `complete ${autoAcceptDiffs}`);
  }
  live.applyMcpLive("server", "read_file", { path: "b.ts" }, "read output");
  t.mock.timers.tick(50);
  assert.equal(useIde.getState().activePath, "new.ts");
  live.applyLiveDraft("write_file", '{"path":"b.ts","content":"stale');
  abortAgent();
  t.mock.timers.tick(50);
  assert.equal(useIde.getState().activePath, "new.ts");
  live.resetLiveWrite();
  beginAgent(); live.resetLiveWrite();
  live.applyLiveDraft("write_file", '{"path":"b.ts","content":"fast');
  live.finishLiveWrite(agentGen());
  t.mock.timers.tick(50);
  assert.equal(live.useLivePreview.getState().streaming, false, "a queued draft cannot reopen after stream completion");
  live.applyLiveDraft("write_file", '{"path":"b.ts","content":"queued');
  await applyWorkspace({ op: "write", path: "b.ts", content: "committed" });
  t.mock.timers.tick(50);
  assert.equal(live.useLivePreview.getState().draft, null, "a queued preview cannot reappear after file adoption");
});
