import assert from "node:assert/strict";
import { test } from "node:test";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { createServer } from "vite";
import { createProjectCheckpoint, previewProjectCheckpoint, restoreProjectCheckpoint, readProjectCheckpointFiles } from "../electron/project-checkpoints.mjs";

test("project round captures assets before work, survives rehydration, protects later edits and restores editor with disk", async (t) => {
  const globals = new Map(["window", "document", "localStorage", "__checkpointRead", "__checkpointSave"].map((key) => [key, globalThis[key]]));
  const output = path.resolve("artifacts/project-checkpoint-integration");
  await mkdir(output, { recursive: true });
  const project = await mkdtemp(path.join(output, "project-"));
  const storageRoot = await mkdtemp(path.join(output, "storage-"));
  const values = new Map(), calls = [];
  let saving = true, slow;
  globalThis.localStorage = { getItem: k => values.get(k) ?? null, setItem: (k,v) => values.set(k,v), removeItem: k => values.delete(k) };
  globalThis.window = Object.assign(new EventTarget(), { localStorage, setTimeout, clearTimeout, anvilNative: { projectCheckpoint: async request => {
    calls.push(request.action);
    const args = { ...request, storageRoot, phase: request.action };
    if (request.action === "preview") return previewProjectCheckpoint(args);
    if (request.action === "restore") return restoreProjectCheckpoint(args);
    if (request.action === "read") return readProjectCheckpointFiles(args);
    if (slow && request.action === "before") await slow;
    return createProjectCheckpoint(args);
  } } });
  globalThis.document = Object.assign(new EventTarget(), { documentElement: { lang: "de" } });
  globalThis.__checkpointSave = async () => saving;
  globalThis.__checkpointRead = async paths => Object.fromEntries(await Promise.all(paths.map(async p => [p, await readFile(path.join(project,p), "utf8").catch(e => { if(e.code === "ENOENT") return null; throw e; })])));
  const server = await createServer({ configFile: false, root: process.cwd(), resolve: { alias: { "@": path.resolve("src") } }, server: { middlewareMode: true, hmr: false, watch: null }, appType: "custom", plugins: [{ name: "checkpoint-boundaries", transform(code,id) {
    if (id.endsWith("/src/lib/save.ts")) return "export const saveNow = (...a) => globalThis.__checkpointSave(...a);";
    if (id.endsWith("/src/lib/companion-life.ts")) return "export const withCompanion = fn => fn();";
    if (id.endsWith("/src/lib/persist-db.ts")) return "export async function saveArchive(){}; export async function loadArchive(){ return {}; }; export async function removeArchive(){};";
    if (id.endsWith("/src/lib/companion.ts")) return code.replace(/export async function companionReadFiles\(/, "async function unusedCompanionReadFiles(") + "\nexport const companionReadFiles = (...args) => globalThis.__checkpointRead(...args);";
  } }] });
  let persistence;
  t.after(async () => { await persistence?.flushPersistence().catch(()=>{}); await server.close(); for(const [k,v] of globals) { if(v===undefined) delete globalThis[k]; else globalThis[k]=v; } });
  const { useIde } = await server.ssrLoadModule("/src/store/ide.ts");
  await useIde.persist.rehydrate();
  persistence = await server.ssrLoadModule("/src/lib/persist-storage.ts");
  const checkpoints = await server.ssrLoadModule("/src/lib/project-checkpoints.ts");
  useIde.setState({ workspaceCwd: project, companionUrl: "http://127.0.0.1:7845", workspaceEpoch: 41, files: { "main.txt": "before" }, dirs: [], dirty: {}, editBases: {}, pendingDiffs: [], checkpoints: [], mcpLog: [], autoSaveDisk: false, agentBusy: false, running: false, pathOperation: null });
  const binary = Buffer.from([0,255,4,9]);
  const binaryUrl = `data:application/octet-stream;base64,${binary.toString("base64")}`;
  await mkdir(path.join(project,"build"));
  await writeFile(path.join(project,"build","cached.txt"),"excluded before");
  useIde.setState({ files: { "main.txt":"before", "asset.bin":binaryUrl, "build/cached.txt":"excluded before" } });
  await writeFile(path.join(project,"main.txt"), "before");
  await writeFile(path.join(project,"asset.bin"), binary);
  const id = useIde.getState().pushCheckpoint("assets round");
  await checkpoints.beginProjectCheckpoint(id);
  assert.equal(useIde.getState().checkpoints[0].disk.status,"before");
  await writeFile(path.join(project,"main.txt"),"after");
  await writeFile(path.join(project,"asset.bin"),Buffer.from([8,7,0]));
  await writeFile(path.join(project,"new.bin"),Buffer.from([99,0]));
  await writeFile(path.join(project,"build","cached.txt"),"excluded after");
  useIde.setState({ files: { "main.txt": "after", "asset.bin":`data:application/octet-stream;base64,${Buffer.from([8,7,0]).toString("base64")}`, "build/cached.txt":"excluded unsaved" }, dirty:{"build/cached.txt":true}, mcpLog:[{at:Date.now(),server:"fixture",name:"update_item",ok:true,detail:"private arguments omitted"}] });
  await checkpoints.sealProjectCheckpoint(id);
  const saved = structuredClone(useIde.getState().checkpoints);
  assert.equal(saved[0].disk.status,"sealed");
  assert.deepEqual(saved[0].externalCalls,[{server:"fixture",name:"update_item",ok:true}]);
  useIde.setState({ checkpoints: saved, workspaceEpoch: 42 });
  assert.equal((await checkpoints.previewProjectRestore(id)).files.length,3);
  await writeFile(path.join(project,"asset.bin"),Buffer.from([88]));
  assert.equal(await useIde.getState().restoreCheckpoint(id),false);
  assert.equal(await readFile(path.join(project,"main.txt"),"utf8"),"after");
  await writeFile(path.join(project,"asset.bin"),Buffer.from([8,7,0]));
  assert.equal(await useIde.getState().restoreCheckpoint(id),true,useIde.getState().notice);
  assert.deepEqual(await readFile(path.join(project,"asset.bin")),binary);
  assert.equal(useIde.getState().files["main.txt"],"before");
  assert.equal(useIde.getState().files["asset.bin"],binaryUrl,"binary RAM stays byte faithful after restore");
  assert.equal(useIde.getState().files["build/cached.txt"],"excluded unsaved");
  assert.equal(useIde.getState().dirty["build/cached.txt"],true,"excluded edits remain unsaved and untouched");
  assert.equal(await readFile(path.join(project,"build","cached.txt"),"utf8"),"excluded after");
  await assert.rejects(readFile(path.join(project,"new.bin")),{code:"ENOENT"});
  assert.equal(await useIde.getState().restoreCheckpoint(id),true,"restoration is idempotent");
  const bad = useIde.getState().pushCheckpoint("failed save");
  saving=false; const count=calls.length;
  await assert.rejects(checkpoints.beginProjectCheckpoint(bad),/Auftrag wurde nicht gestartet/);
  assert.equal(calls.length,count,"never snapshot or start work after failed save");
  assert.equal(useIde.getState().checkpoints.find(c=>c.id===bad).disk.status,"error");
  saving=true;
  const changed=useIde.getState().pushCheckpoint("workspace race");
  let release; slow=new Promise(resolve=>{release=resolve;});
  const pending=checkpoints.beginProjectCheckpoint(changed);
  while(calls.length===count) await new Promise(resolve=>setImmediate(resolve));
  useIde.setState({workspaceEpoch:43}); release(); slow=undefined;
  await assert.rejects(pending,/Projekt während/);
  await assert.rejects(checkpoints.previewProjectRestore(changed),/Projekt während/);
});
